### ISSUE TITLE
NesHawk Game Genie codes will not turn off

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#780]
Game Genie codes will not turn off even when you turn them off or delete them. Like on the game Jackal (USA)

Both players have infinite lives code.

SZPTSI

http://gamehacking.org/game/29932

**Comment by hegyak** [comment]
Wasn't this resolved in this Commit?
https://github.com/TASVideos/BizHawk/commit/d0b094622936031a813df460d3bb43d72dc9ccc2

And this is related to this Bug Report:
https://github.com/TASVideos/BizHawk/issues/770

**Comment by alyosha-tas** [comment]
Just tested this with latest dev build.

Cheat on gives infiinite lives, turning if off made lives decrease as expected.

Did you test this on the latest build?

**Comment by Cibomatto2002** [comment]
Was tested on the latest dev build.

When I tried the game  Jackal (USA) the bug was still there if the code is turned on then shut down the Emulator reset it the bug is still there. The last BizHawk update I got was * Update NES.Core.cs
* NES DCM glitch cleanup
-Implemenet for player 2
-make sure only happens on NTSC

**Comment by alyosha-tas** [comment]
Are you sure you are using NESHawk? 

This bug is not fixed on QuickNES.

**Comment by Cibomatto2002** [comment]
I'm sorry I was using QuickNES.

**Comment by Cibomatto2002** [comment]
Which ones is the best to use NESHawk or QuickNES?

**Comment by alyosha-tas** [comment]
NESHawk is more accurate and has higher compatibility, also it is actively maintained.

QuickNES is quick, 2x as fast as NESHawk or more, so might be better for certain applications (ex. AI stuff)

Use whichever you like, but generally if something doesn't work in QuickNES it will work (or I will make it work) in NESHawk.

**Comment by Cibomatto2002** [comment]
So really no one needs to use QuickNES because NESHawk is better. Is NESHawk better than FCEUX?

**Comment by alyosha-tas** [comment]
NESHawk is more accurate then FCEUX. So when accuracy matters, use NESHawk. 

For casual gaming they should be equally good. FCEUX is more user friendly in general, but NESHawk has slowly been catching up.

**Comment by Cibomatto2002** [comment]
Is there any plans to add more consoles to BizHawk? I would like to see the odyssey 2 added one day.

**Comment by alyosha-tas** [comment]
Consoles are added has people have the time/motivation to add them. I'm not aware of any particular time table.

**Comment by Cibomatto2002** [comment]
Do the cores get updated often?   I see some of the Emulators have updated.

**Comment by hegyak** [comment]
Depends on what changed/updated.  And the developers have to port the new updated emulator to BizHawk.  Sometimes it's easy, like a .Net Core (Usually).  Sometimes, it's Pain Incarnate (Newer BSNES).

This is a document that has been around for a quite a while if your curious as to what makes a good core to port/implement into BizHawk:
https://github.com/TASVideos/BizHawk/blob/master/Good%20Core%20Bad%20Core.txt

**Comment by Cibomatto2002** [comment]
That was some good reading. I understand more about it now Thanks.
